version: '3'
services:
  web:
    build: .
    volumes:
      - .:/tracer
    ports:
      - "3000:3000"
    command: bin/rails server -p 3000 -b '0.0.0.0'
  dev:
    build: .
    volumes:
      - .:/tracer
    command: /bin/bash